## Project-1: Data Cleaning & Preparation

This project focuses on cleaning and preparing an e-commerce dataset. The objective is to identify and resolve data quality issues such as missing values, duplicate records, and inconsistencies to ensure the dataset is reliable and ready for analysis.

### Importing Required Libraries

In [1]:
import pandas as pd

### Loading the Dataset into a Pandas DataFrame

In [2]:
df=pd.read_excel("Dataset for Data Analytics.xlsx")

### Data Inspection

In [3]:
df.head(7)

,OrderID,Date,CustomerID,Product,Quantity,UnitPrice,ShippingAddress,PaymentMethod,OrderStatus,TrackingNumber,ItemsInCart,CouponCode,ReferralSource,TotalPrice
0,ORD200000,2023-01-04,C72649,Monitor,5,570.62,928 Main St,Debit Card,Shipped,TRK37947903,7,SAVE10,Instagram,2853.10
1,ORD200001,2024-08-23,C75739,Phone,2,151.35,823 Main St,Online,Shipped,TRK91186779,3,SAVE10,Referral,302.70
2,ORD200002,2024-02-27,C81728,Tablet,5,550.68,512 Main St,Credit Card,Cancelled,TRK42903982,8,FREESHIP,Email,2753.40
3,ORD200003,2023-10-15,C33540,Chair,1,273.19,275 Main St,Debit Card,Returned,TRK62788070,5,SAVE10,Facebook,273.19
4,ORD200004,2025-05-08,C81840,Printer,4,626.01,668 Main St,Online,Delivered,TRK29241424,8,SAVE10,Email,2504.04
5,ORD200005,2023-10-23,C37249,Phone,2,245.86,934 Main St,Credit Card,Shipped,TRK72976927,4,SAVE10,Instagram,491.72
6,ORD200006,2025-06-17,C83492,Laptop,1,664.42,986 Main St,Gift Card,Returned,TRK96417362,6,SAVE10,Facebook,664.42

In [4]:
df.tail()

,OrderID,Date,CustomerID,Product,Quantity,UnitPrice,ShippingAddress,PaymentMethod,OrderStatus,TrackingNumber,ItemsInCart,CouponCode,ReferralSource,TotalPrice
1195,ORD201195,2024-06-20,C21126,Desk,1,107.04,392 Main St,Credit Card,Cancelled,TRK38009181,6,FREESHIP,Google,107.04
1196,ORD201196,2024-03-04,C20095,Monitor,2,662.53,778 Main St,Online,Cancelled,TRK69207593,5,NaN,Facebook,1325.06
1197,ORD201197,2023-07-13,C79674,Tablet,2,436.84,275 Main St,Online,Delivered,TRK88039356,2,FREESHIP,Instagram,873.68
1198,ORD201198,2024-08-22,C64753,Chair,4,262.52,509 Main St,Debit Card,Cancelled,TRK71683331,4,WINTER15,Instagram,1050.08
1199,ORD201199,2023-06-11,C57502,Tablet,4,560.58,201 Main St,Gift Card,Returned,TRK51116746,6,SAVE10,Referral,2242.32

In [5]:
df.shape

(1200, 14)

In [6]:
df.columns

Index(['OrderID', 'Date', 'CustomerID', 'Product', 'Quantity', 'UnitPrice',
       'ShippingAddress', 'PaymentMethod', 'OrderStatus', 'TrackingNumber',
       'ItemsInCart', 'CouponCode', 'ReferralSource', 'TotalPrice'],
      dtype='str')

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1200 entries, 0 to 1199
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   OrderID          1200 non-null   str
 1   Date             1200 non-null   datetime64[us]
 2   CustomerID       1200 non-null   str
 3   Product          1200 non-null   str
 4   Quantity         1200 non-null   int64
 5   UnitPrice        1200 non-null   float64
 6   ShippingAddress  1200 non-null   str
 7   PaymentMethod    1200 non-null   str
 8   OrderStatus      1200 non-null   str
 9   TrackingNumber   1200 non-null   str
 10  ItemsInCart      1200 non-null   int64
 11  CouponCode       891 non-null    str
 12  ReferralSource   1200 non-null   str
 13  TotalPrice       1200 non-null   float64
dtypes: datetime64[us](1), float64(2), int64(2), str(9)
memory usage: 215.1 KB

In [8]:
df.describe()

                      Date     Quantity    UnitPrice  ItemsInCart   TotalPrice
count                 1200  1200.000000  1200.000000  1200.000000  1200.000000
mean   2024-03-22 16:58:48     2.945833   356.412750     5.485000  1053.968300
min    2023-01-01 00:00:00     1.000000    11.390000     1.000000    11.390000
25%    2023-08-03 18:00:00     2.000000   186.062500     4.000000   410.520000
50%    2024-03-23 00:00:00     3.000000   364.210000     5.000000   823.615000
75%    2024-11-08 12:00:00     4.000000   521.570000     7.000000  1578.475000
max    2025-06-30 00:00:00     5.000000   699.930000    10.000000  3456.400000
std                    NaN     1.407557   197.177146     2.281983   819.856558

### Data Cleaning

### Identifying Missing Values

In [9]:
df.isnull().sum()

OrderID              0
Date                 0
CustomerID           0
Product              0
Quantity             0
UnitPrice            0
ShippingAddress      0
PaymentMethod        0
OrderStatus          0
TrackingNumber       0
ItemsInCart          0
CouponCode         309
ReferralSource       0
TotalPrice           0
dtype: int64

### Handling Missing Values in CouponCode

In [10]:
df['CouponCode']=df['CouponCode'].fillna('NO COUPON')

In [11]:
df.isnull().sum()

OrderID            0
Date               0
CustomerID         0
Product            0
Quantity           0
UnitPrice          0
ShippingAddress    0
PaymentMethod      0
OrderStatus        0
TrackingNumber     0
ItemsInCart        0
CouponCode         0
ReferralSource     0
TotalPrice         0
dtype: int64

### Check for Duplicate Values

In [12]:
print(df.duplicated().sum())

0

In [13]:
print(df['OrderID'].duplicated().sum())

0

In [14]:
print(df['OrderID'].nunique())

1200

In [15]:
print(df['CustomerID'].duplicated().sum())

11

In [16]:
print(df['CustomerID'].nunique())

1189

### Observation

The OrderID column has no duplicates it uniquely identifies 1200 rows whereas the CustomerID column contains 11 repeated values, it can be possible because a single customer can place multiple orders.

### Data Validation

In [17]:
df['Quantity'].describe()

count    1200.000000
mean        2.945833
std         1.407557
min         1.000000
25%         2.000000
50%         3.000000
75%         4.000000
max         5.000000
Name: Quantity, dtype: float64

In [18]:
df['UnitPrice'].describe()

count    1200.000000
mean      356.412750
std       197.177146
min        11.390000
25%       186.062500
50%       364.210000
75%       521.570000
max       699.930000
Name: UnitPrice, dtype: float64

In [19]:
df['CalculatedPrice']=df['Quantity']*df['UnitPrice']

In [20]:
print((df['CalculatedPrice']!=df['TotalPrice']).sum())

107

In [21]:
print((round(df['CalculatedPrice'],2)!=round(df['TotalPrice'],2)).sum())

0

In [22]:
df=df.drop(columns=['CalculatedPrice'])

In [23]:
df.shape

(1200, 14)

### Total Price Validation

The TotalPrice column was validated by recalculating order values using Quantity and UnitPrice.
The CalculatedPrice column was removed after validation.

In [24]:
print((df['Quantity']>df['ItemsInCart']).sum())

0

### Validate Categorical Columns

In [25]:
df['Product'].unique()

<ArrowStringArray>
['Monitor', 'Phone', 'Tablet', 'Chair', 'Printer', 'Laptop', 'Desk']
Length: 7, dtype: str

In [26]:
df['PaymentMethod'].unique()

<ArrowStringArray>
['Debit Card', 'Online', 'Credit Card', 'Gift Card', 'Cash']
Length: 5, dtype: str

In [27]:
df['OrderStatus'].unique()

<ArrowStringArray>
['Shipped', 'Cancelled', 'Returned', 'Delivered', 'Pending']
Length: 5, dtype: str

In [28]:
df['ReferralSource'].unique()

<ArrowStringArray>
['Instagram', 'Referral', 'Email', 'Facebook', 'Google']
Length: 5, dtype: str

In [29]:
df['CouponCode'].unique()

<ArrowStringArray>
['SAVE10', 'FREESHIP', 'NO COUPON', 'WINTER15']
Length: 4, dtype: str

### Observation

The categorical columns were examined for inconsistencies in spelling, capitalization, and formatting.

### Data Preparation

### Feature Creation from Date Column

Additional date-based features were created from the Date column, including Year and Month for future analysis.

In [30]:
df['Year']=df['Date'].dt.year

In [31]:
df['Month']=df['Date'].dt.month

In [32]:
df.shape

(1200, 16)

### Save the Cleaned Dataset

In [58]:
df.to_excel('cleaned_dataset.xlsx',index=False)

### Summary

- Loaded and examined the e-commerce dataset.
- Handled missing values in the CouponCode column.
- Checked for duplicate records and validated data uniqueness.
- Verified Quantity, UnitPrice, and TotalPrice values.
- Validated logical consistency between Quantity and ItemsInCart.
- Checked categorical columns for formatting and consistency issues.
- Created Year and Month features from the Date column for improved data usability.
- Saved the cleaned and prepared dataset for future analysis.